// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// splitPrc_cpp
Rcpp::List splitPrc_cpp(arma::vec X);
RcppExport SEXP EMbC_splitPrc_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(splitPrc_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// bound2R_cpp
Rcpp::LogicalVector bound2R_cpp(Rcpp::NumericMatrix X, Rcpp::NumericVector Rk);
RcppExport SEXP EMbC_bound2R_cpp(SEXP XSEXP, SEXP RkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Rk(RkSEXP);
    rcpp_result_gen = Rcpp::wrap(bound2R_cpp(X, Rk));
    return rcpp_result_gen;
END_RCPP
}
// getClusters_cpp
Rcpp::NumericVector getClusters_cpp(arma::mat X, arma::mat U, arma::mat W, arma::mat R);
RcppExport SEXP EMbC_getClusters_cpp(SEXP XSEXP, SEXP USEXP, SEXP WSEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type U(USEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(getClusters_cpp(X, U, W, R));
    return rcpp_result_gen;
END_RCPP
}
// dens2wght_cpp
arma::mat dens2wght_cpp(arma::mat L);
RcppExport SEXP EMbC_dens2wght_cpp(SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(dens2wght_cpp(L));
    return rcpp_result_gen;
END_RCPP
}
// getLkh_cpp
double getLkh_cpp(arma::mat L);
RcppExport SEXP EMbC_getLkh_cpp(SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(getLkh_cpp(L));
    return rcpp_result_gen;
END_RCPP
}
